import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export interface GeneratedFile {
  path: string;
  content: string;
}

function writeFiles(baseDir: string, files: GeneratedFile[]): void {
  for (const file of files) {
    const full = join(baseDir, file.path);
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, file.content, "utf8");
  }
}

export function generateAgent(name: string, baseDir: string): void {
  const slug = name.toLowerCase().replace(/\s+/g, "_");
  const files: GeneratedFile[] = [
    {
      path: "agent.json",
      content: JSON.stringify(
        {
          name,
          slug,
          version: "1.0.0",
          capabilities: ["task_execution", "tool_use"],
          permissions: ["read", "execute"],
          skills: ["teach-concept"],
          status: "active",
        },
        null,
        2
      ),
    },
    {
      path: "src/agent.ts",
      content: `// ${name} — Buselligence Agent
export const agent = {
  slug: "${slug}",
  name: "${name}",
  async execute(ctx: { input: string }) {
    return ctx.input;
  },
};
`,
    },
    {
      path: "README.md",
      content: `# ${name}

Buselligence agent scaffold. Register via kernel or deploy to your runtime.

\`\`\`bash
bus test agent ${slug}
bus evaluate ${slug} "Complete a sample task"
\`\`\`
`,
    },
    {
      path: "buselligence.lock",
      content: JSON.stringify(
        {
          version: "1.0.0",
          agents: { [slug]: "1.0.0" },
          skills: { "teach-concept": "1.0.0" },
          models: { default: "gpt-4o-mini" },
          dependencies: { buselligence: "8.0.0", kernel: "1.0.0" },
        },
        null,
        2
      ),
    },
  ];
  writeFiles(baseDir, files);
}

export function generateApp(name: string, baseDir: string): void {
  const files: GeneratedFile[] = [
    {
      path: "package.json",
      content: JSON.stringify({ name, version: "1.0.0", private: true, type: "module" }, null, 2),
    },
    {
      path: "src/index.ts",
      content: `// ${name} — generated by Buselligence CLI
console.log("${name} running on Buselligence runtime");
`,
    },
    {
      path: "README.md",
      content: `# ${name}\n\nAI app scaffold. Run with \`bus deploy\`.\n`,
    },
    {
      path: "buselligence.lock",
      content: JSON.stringify(
        { version: "1.0.0", skills: { "build-react-app": "1.0.0" }, dependencies: { buselligence: "8.0.0" } },
        null,
        2
      ),
    },
  ];
  writeFiles(baseDir, files);
}

export function generateAiApp(name: string, baseDir: string, type = "crm"): void {
  const isCrm = type === "crm" || name.toLowerCase().includes("crm");
  const appName = isCrm ? "CRM" : name;

  const files: GeneratedFile[] = [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: name.toLowerCase().replace(/\s+/g, "-"),
          version: "1.0.0",
          private: true,
          scripts: { dev: "vite", test: "vitest run" },
        },
        null,
        2
      ),
    },
    {
      path: "buselligence.lock",
      content: JSON.stringify(
        {
          version: "1.0.0",
          models: { default: "gpt-4o-mini", reasoning: "gpt-4o" },
          agents: { business_analyst: "1.0.0", software_engineer: "1.0.0" },
          skills: { "generate-api": "1.0.0", "analyze-database": "1.0.0", "build-react-app": "1.0.0" },
          mcpServers: [],
          dependencies: { buselligence: "8.0.0", kernel: "1.0.0" },
        },
        null,
        2
      ),
    },
    {
      path: "agent/agent.json",
      content: JSON.stringify(
        {
          name: `${appName} Agent`,
          slug: `${name.toLowerCase().replace(/\s+/g, "_")}_agent`,
          capabilities: ["customer_insights", "pipeline_analysis", "automation"],
          permissions: ["read:data", "write:crm", "execute:workflows"],
        },
        null,
        2
      ),
    },
    {
      path: "schema/database.sql",
      content: `-- ${appName} database schema
CREATE TABLE customers (id UUID PRIMARY KEY, company TEXT, email TEXT, status TEXT);
CREATE TABLE opportunities (id UUID PRIMARY KEY, customer_id UUID, title TEXT, value DECIMAL, stage TEXT);
CREATE TABLE activities (id UUID PRIMARY KEY, opportunity_id UUID, type TEXT, notes TEXT, created_at TIMESTAMP);
CREATE TABLE users (id UUID PRIMARY KEY, email TEXT, role TEXT);
`,
    },
    {
      path: "src/ui/Dashboard.tsx",
      content: `export function Dashboard() {
  return (
    <div>
      <h1>${appName} Dashboard</h1>
      <p>Pipeline · Customers · Activities — powered by Buselligence</p>
    </div>
  );
}
`,
    },
    {
      path: "src/api/routes.ts",
      content: `// ${appName} REST API
export const routes = [
  { method: "GET", path: "/api/customers", handler: "listCustomers" },
  { method: "POST", path: "/api/customers", handler: "createCustomer" },
  { method: "GET", path: "/api/opportunities", handler: "listOpportunities" },
];
`,
    },
    {
      path: "tests/app.test.ts",
      content: `import { describe, it, expect } from "vitest";

describe("${appName}", () => {
  it("loads dashboard", () => {
    expect(true).toBe(true);
  });
});
`,
    },
    {
      path: "docs/README.md",
      content: `# ${appName} Documentation

Generated by \`bus create ${name} --ai\`.

## Architecture

- **Agent** — AI-powered business logic in \`agent/\`
- **API** — REST endpoints in \`src/api/\`
- **UI** — React dashboard in \`src/ui/\`
- **Database** — Schema in \`schema/database.sql\`
- **Tests** — Vitest in \`tests/\`
`,
    },
    {
      path: "README.md",
      content: `# ${appName}

Full-stack AI application generated by Buselligence CLI.

## Generated structure

- Project structure
- Agent configuration
- Database schema
- UI components
- API routes
- Tests
- Documentation

\`\`\`bash
bus deploy
bus test agent ${name.toLowerCase().replace(/\s+/g, "_")}_agent
\`\`\`

Built with [Buselligence](https://github.com/Salestrics/Buselligence) AI Runtime.
`,
    },
  ];
  writeFiles(baseDir, files);
}

export function ensureDir(dir: string): void {
  if (existsSync(dir)) {
    throw new Error(`Directory already exists: ${dir}`);
  }
  mkdirSync(dir, { recursive: true });
}
