import { randomUUID } from "node:crypto";
import { db } from "../db.js";
import { parseJson } from "./schema.js";
import { parseIdea } from "./parser.js";
import { createBlueprint, createPreview, createRoadmap, type ProjectBlueprint } from "./blueprint.js";
import { createProject, createFile } from "../studio/manager.js";
import { kernelExecute } from "../kernel/kernel.js";
import { storeMemory } from "../core/runtime.js";
import type { FileLanguage } from "../studio/types.js";

export interface BuildStats {
  filesCreated: number;
  testsPassing: number;
  aiDecisions: number;
}

export interface BuildEvent {
  type: "agent" | "file" | "test" | "decision" | "progress" | "blueprint" | "roadmap" | "complete" | "phase";
  agent?: string;
  agentEmoji?: string;
  message: string;
  file?: string;
  progress?: number;
  timestamp: string;
}

export interface GenesisBuild {
  id: string;
  prompt: string;
  projectName: string;
  status: "pending" | "building" | "completed" | "failed";
  progress: number;
  currentAgent?: string;
  currentFile?: string;
  blueprint: ProjectBlueprint;
  roadmap: ReturnType<typeof createRoadmap>;
  stats: BuildStats;
  studioProjectId?: string;
  preview: ReturnType<typeof createPreview>;
  events: BuildEvent[];
}

const AGENTS = [
  { id: "architect", name: "AI Architect", emoji: "🏗", role: "Architect" },
  { id: "product_manager", name: "AI Product Manager", emoji: "📋", role: "Product Manager" },
  { id: "database_engineer", name: "Database Engineer", emoji: "🗄", role: "Database Engineer" },
  { id: "backend_engineer", name: "Backend Engineer", emoji: "⚙", role: "Backend Engineer" },
  { id: "frontend_engineer", name: "Frontend Engineer", emoji: "💻", role: "Frontend Engineer" },
  { id: "qa_engineer", name: "QA Engineer", emoji: "🧪", role: "QA Engineer" },
] as const;

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function generateFiles(idea: ReturnType<typeof parseIdea>): Array<{ path: string; content: string; language: FileLanguage }> {
  const name = idea.projectName;
  const files: Array<{ path: string; content: string; language: FileLanguage }> = [];

  files.push({
    path: "README.md",
    language: "markdown",
    content: `# ${name}\n\nGenerated by Buselligence Build Anything Mode.\n\n${idea.modules.join(" · ")}\n`,
  });

  files.push({
    path: "buselligence.lock",
    language: "json",
    content: JSON.stringify(
      {
        version: "1.0.0",
        project: name,
        agents: { architect: "1.0.0", software_engineer: "1.0.0" },
        skills: { "build-react-app": "1.0.0", "generate-api": "1.0.0", "analyze-database": "1.0.0" },
        models: { default: "gpt-4o-mini", reasoning: "gpt-4o" },
      },
      null,
      2
    ),
  });

  files.push({
    path: "schema/database.sql",
    language: "sql",
    content: `-- ${name} database schema
CREATE TABLE tenants (id UUID PRIMARY KEY, name TEXT, plan TEXT);
CREATE TABLE users (id UUID PRIMARY KEY, tenant_id UUID, email TEXT, role TEXT);
${idea.modules.map((m) => `CREATE TABLE ${m.toLowerCase()} (id UUID PRIMARY KEY, tenant_id UUID, name TEXT, data JSONB);`).join("\n")}
CREATE TABLE audit_log (id UUID PRIMARY KEY, action TEXT, user_id UUID, created_at TIMESTAMP);
`,
  });

  for (const mod of idea.modules) {
    const slug = mod.toLowerCase();
    files.push({
      path: `src/api/${slug}.ts`,
      language: "typescript",
      content: `// ${mod} API — ${name}
import { Router } from "express";
export const ${slug}Router = Router();

${slug}Router.get("/", async (_req, res) => {
  res.json({ module: "${mod}", items: [] });
});

${slug}Router.post("/", async (req, res) => {
  res.status(201).json({ created: true, ...req.body });
});
`,
    });

    files.push({
      path: `src/components/${slug}/Table.tsx`,
      language: "typescript",
      content: `// ${mod} table component
export function ${mod}Table() {
  return (
    <div className="${slug}-table">
      <h2>${mod}</h2>
      <table><thead><tr><th>Name</th><th>Status</th></tr></thead><tbody /></table>
    </div>
  );
}
`,
    });

    files.push({
      path: `tests/${slug}.test.ts`,
      language: "typescript",
      content: `import { describe, it, expect } from "vitest";
describe("${mod}", () => {
  it("loads ${slug} module", () => { expect(true).toBe(true); });
  it("validates ${slug} API", () => { expect("${mod}").toBeTruthy(); });
});
`,
    });
  }

  files.push({
    path: "src/pages/Dashboard.tsx",
    language: "typescript",
    content: `// ${name} Dashboard
export function Dashboard() {
  return (
    <div>
      <h1>${name}</h1>
      <nav>${idea.modules.map((m) => `<a href="/${m.toLowerCase()}">${m}</a>`).join(" · ")}</nav>
    </div>
  );
}
`,
  });

  files.push({
    path: "src/auth/permissions.ts",
    language: "typescript",
    content: `export const ROLES = ["admin", "manager", "staff", "viewer"] as const;
export type Role = typeof ROLES[number];
export function canAccess(role: Role, resource: string): boolean {
  if (role === "admin") return true;
  return resource !== "settings";
}
`,
  });

  files.push({
    path: "src/ai/assistant.ts",
    language: "typescript",
    content: `// AI Assistant — powered by Buselligence Kernel
export async function askAssistant(question: string) {
  return { answer: \`AI insight for: \${question}\`, module: "${name}" };
}
`,
  });

  return files;
}

export function startBuild(userId: string, prompt: string): GenesisBuild {
  const idea = parseIdea(prompt);
  const blueprint = createBlueprint(idea);
  const roadmap = createRoadmap(idea);
  const preview = createPreview(idea);
  const id = randomUUID();

  db.prepare(
    `INSERT INTO genesis_builds (id, user_id, prompt, project_name, status, blueprint, roadmap, preview, stats)
     VALUES (?, ?, ?, ?, 'pending', ?, ?, ?, ?)`
  ).run(
    id,
    userId,
    prompt,
    idea.projectName,
    JSON.stringify(blueprint),
    JSON.stringify(roadmap),
    JSON.stringify(preview),
    JSON.stringify({ filesCreated: 0, testsPassing: 0, aiDecisions: 0 })
  );

  return getBuild(userId, id)!;
}

export function getBuild(userId: string, buildId: string): GenesisBuild | null {
  const row = db
    .prepare("SELECT * FROM genesis_builds WHERE id = ? AND user_id = ?")
    .get(buildId, userId) as {
    id: string;
    prompt: string;
    project_name: string;
    status: string;
    progress: number;
    current_agent: string | null;
    current_file: string | null;
    blueprint: string;
    roadmap: string;
    stats: string;
    studio_project_id: string | null;
    preview: string;
    events: string;
  } | undefined;

  if (!row) return null;

  return {
    id: row.id,
    prompt: row.prompt,
    projectName: row.project_name,
    status: row.status as GenesisBuild["status"],
    progress: row.progress,
    currentAgent: row.current_agent ?? undefined,
    currentFile: row.current_file ?? undefined,
    blueprint: parseJson(row.blueprint, {} as ProjectBlueprint),
    roadmap: parseJson(row.roadmap, { sprints: [] }),
    stats: parseJson<BuildStats>(row.stats, { filesCreated: 0, testsPassing: 0, aiDecisions: 0 }),
    studioProjectId: row.studio_project_id ?? undefined,
    preview: parseJson(row.preview, { title: "", navigation: [] }),
    events: parseJson<BuildEvent[]>(row.events, []),
  };
}

export function listBuilds(userId: string): GenesisBuild[] {
  const rows = db
    .prepare("SELECT id FROM genesis_builds WHERE user_id = ? ORDER BY created_at DESC LIMIT 10")
    .all(userId) as Array<{ id: string }>;
  return rows.map((r) => getBuild(userId, r.id)!).filter(Boolean);
}

function persistBuild(
  buildId: string,
  patch: Partial<{
    status: string;
    progress: number;
    current_agent: string | null;
    current_file: string | null;
    stats: BuildStats;
    studio_project_id: string;
    events: BuildEvent[];
    roadmap: ReturnType<typeof createRoadmap>;
  }>
): void {
  const sets: string[] = ["updated_at = datetime('now')"];
  const values: unknown[] = [];

  if (patch.status !== undefined) {
    sets.push("status = ?");
    values.push(patch.status);
  }
  if (patch.progress !== undefined) {
    sets.push("progress = ?");
    values.push(patch.progress);
  }
  if (patch.current_agent !== undefined) {
    sets.push("current_agent = ?");
    values.push(patch.current_agent);
  }
  if (patch.current_file !== undefined) {
    sets.push("current_file = ?");
    values.push(patch.current_file);
  }
  if (patch.stats) {
    sets.push("stats = ?");
    values.push(JSON.stringify(patch.stats));
  }
  if (patch.studio_project_id) {
    sets.push("studio_project_id = ?");
    values.push(patch.studio_project_id);
  }
  if (patch.events) {
    sets.push("events = ?");
    values.push(JSON.stringify(patch.events));
  }
  if (patch.roadmap) {
    sets.push("roadmap = ?");
    values.push(JSON.stringify(patch.roadmap));
  }

  values.push(buildId);
  db.prepare(`UPDATE genesis_builds SET ${sets.join(", ")} WHERE id = ?`).run(...values);
}

export async function* runGenesisBuild(
  userId: string,
  buildId: string
): AsyncGenerator<BuildEvent> {
  const build = getBuild(userId, buildId);
  if (!build) throw new Error("Build not found");

  const idea = parseIdea(build.prompt);
  const events: BuildEvent[] = [];
  const stats: BuildStats = { filesCreated: 0, testsPassing: 0, aiDecisions: 0 };

  const emit = function* (event: Omit<BuildEvent, "timestamp">): Generator<BuildEvent> {
    const full: BuildEvent = { ...event, timestamp: new Date().toISOString() };
    events.push(full);
    yield full;
  };

  persistBuild(buildId, { status: "building", progress: 0, events });

  // Phase 1: Architect
  const architect = AGENTS[0]!;
  for (const e of emit({
    type: "phase",
    agent: architect.name,
    agentEmoji: architect.emoji,
    message: `${architect.emoji} ${architect.name} — Designing system architecture...`,
    progress: 5,
  })) {
    yield e;
  }
  persistBuild(buildId, { current_agent: architect.name, progress: 5, events });

  await delay(400);

  for (const item of build.blueprint.architecture) {
    stats.aiDecisions++;
    for (const e of emit({
      type: "decision",
      agent: architect.name,
      agentEmoji: architect.emoji,
      message: `✓ ${item}`,
      progress: Math.min(12, 5 + stats.aiDecisions),
    })) {
      yield e;
    }
    await delay(120);
  }

  for (const e of emit({
    type: "blueprint",
    agent: architect.name,
    message: `Project Blueprint: ${build.projectName}`,
    progress: 15,
  })) {
    yield e;
  }
  persistBuild(buildId, { progress: 15, stats, events });

  // Phase 2: Product Manager
  const pm = AGENTS[1]!;
  for (const e of emit({
    type: "phase",
    agent: pm.name,
    agentEmoji: pm.emoji,
    message: `${pm.emoji} ${pm.name} — Creating product roadmap...`,
    progress: 18,
  })) {
    yield e;
  }
  persistBuild(buildId, { current_agent: pm.name, progress: 18, events });

  await delay(350);
  const roadmap = { ...build.roadmap };
  for (const sprint of roadmap.sprints) {
    sprint.status = "active";
    for (const task of sprint.tasks) {
      stats.aiDecisions++;
      for (const e of emit({
        type: "decision",
        agent: pm.name,
        agentEmoji: pm.emoji,
        message: `Sprint ${sprint.number}: ✓ ${task}`,
        progress: 18 + sprint.number * 2,
      })) {
        yield e;
      }
      await delay(100);
    }
    sprint.status = "completed";
  }

  for (const e of emit({ type: "roadmap", agent: pm.name, message: "Product roadmap complete", progress: 25 })) {
    yield e;
  }
  persistBuild(buildId, { progress: 25, stats, events, roadmap });

  // Create studio project
  const studioProject = createProject(userId, {
    name: build.projectName,
    description: build.prompt,
    projectType: "app",
    stack: build.blueprint.stack,
  });

  persistBuild(buildId, { studio_project_id: studioProject.id, events });

  const allFiles = generateFiles(idea);
  const fileAgents = AGENTS.slice(2);

  let progress = 28;
  const progressPerFile = Math.floor(65 / allFiles.length);

  for (const file of allFiles) {
    const agent =
      file.path.includes("schema") || file.path.endsWith(".sql")
        ? fileAgents[0]
        : file.path.includes("api/")
          ? fileAgents[1]
          : file.path.includes("test")
            ? fileAgents[3]
            : fileAgents[2];

    for (const e of emit({
      type: "agent",
      agent: agent!.name,
      agentEmoji: agent!.emoji,
      message: `${agent!.emoji} ${agent!.role} — Working on ${file.path}`,
      progress,
    })) {
      yield e;
    }

    createFile(userId, studioProject.id, file.path, file.content, file.language);
    stats.filesCreated++;

    for (const e of emit({
      type: "file",
      agent: agent!.name,
      agentEmoji: agent!.emoji,
      message: `Creating: ${file.path}`,
      file: file.path,
      progress: progress + 1,
    })) {
      yield e;
    }

    if (file.path.includes("test")) {
      stats.testsPassing += 2;
      for (const e of emit({
        type: "test",
        agent: "QA Engineer",
        agentEmoji: "🧪",
        message: `Tests: ${stats.testsPassing} passing`,
        progress: progress + 2,
      })) {
        yield e;
      }
    }

    progress = Math.min(92, progress + progressPerFile);
    persistBuild(buildId, {
      current_agent: agent!.name,
      current_file: file.path,
      progress,
      stats,
      events,
    });

    await delay(180);
  }

  // Kernel execution trace
  stats.aiDecisions++;
  await kernelExecute(userId, {
    action: "genesis_build",
    input: { projectName: build.projectName, modules: idea.modules },
    agentId: "software_engineer",
  });

  storeMemory(userId, `genesis:${build.projectName}`, build.prompt, "decision", studioProject.id);

  for (const e of emit({
    type: "complete",
    message: "Your application is ready.",
    progress: 100,
  })) {
    yield e;
  }

  persistBuild(buildId, {
    status: "completed",
    progress: 100,
    current_agent: null,
    current_file: null,
    stats,
    events,
  });
}
