import { listFiles } from "./manager.js";
import type { StudioProject } from "./types.js";

export interface GeneratedDocs {
  readme: string;
  apiDocs: string;
  architecture: string;
  releaseNotes: string;
}

export function generateDocs(
  project: StudioProject,
  userId: string
): GeneratedDocs {
  const files = listFiles(userId, project.id);
  const apiFiles = files.filter((f) => f.path.includes("api/"));
  const sqlFiles = files.filter((f) => f.path.endsWith(".sql"));

  const readme = `# ${project.name}

${project.description ?? "Built with Buselligence Studio."}

## Stack

${project.stack.map((s) => `- ${s}`).join("\n")}

## Project Structure

${files.map((f) => `- \`${f.path}\``).join("\n")}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Deployment

Deploy via Buselligence Studio → Deploy → Production

---
*Generated by Buselligence Documentation Generator*
`;

  const apiDocs = `# API Documentation — ${project.name}

${apiFiles.length ? apiFiles.map((f) => `## ${f.path}\n\n\`\`\`typescript\n${f.content.slice(0, 500)}\n\`\`\``).join("\n\n") : "No API endpoints defined yet."}

## Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | /api/health | Health check |
${apiFiles.map((f) => `| * | ${f.path.replace("src", "")} | Auto-generated |`).join("\n")}
`;

  const architecture = `# Architecture — ${project.name}

## Overview

${project.name} is a ${project.projectType} built on the Buselligence platform.

## Data Layer

${sqlFiles.length ? sqlFiles.map((f) => `### ${f.path}\n\`\`\`sql\n${f.content.slice(0, 300)}\n\`\`\``).join("\n\n") : "No database schema defined."}

## Components

${files.filter((f) => f.path.includes("components/")).map((f) => `- ${f.path}`).join("\n") || "No components yet."}

## Integrations

- Semantic Layer metrics
- Data connectors (PostgreSQL, Stripe, Salesforce)
- MCP tools
`;

  const releaseNotes = `# Release Notes — v1.0.0

## ${new Date().toISOString().split("T")[0]}

### Added
- Initial project scaffold: ${project.name}
- ${files.length} files generated
- ${project.stack.join(", ")} stack

### Generated by
Buselligence AI Documentation Generator
`;

  return { readme, apiDocs, architecture, releaseNotes };
}
